pre-commit:
  parallel: true
  commands:
    shellcheck:
      run: ./run lint:shell
    check_unencrypted_drafts:
      run: ./run check_unencrypted

pre-push:
  commands:
    check_encrypted_drafts:
      files: find . -mindepth 2 -type f -name "*.md" -not -path "./.git/*"
      run: ./run check_unencrypted {files}
